server:
  port: 8029

spring:
  profiles:
    active: dev
  main.allow-bean-definition-overriding: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://10.100.10.44:8999/auth/realms/spring-micro-main
  web:
    locale-resolver: accept_header
    locale: uz

  ### DataSource
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@db.mib.uz:1521:mib1
    username: dbdockeruser
    password: dbdocker123

### Mybatis
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations:
    - classpath:mappers/*Mapper.xml
    - classpath:mappers/crud/*Mapper.xml

mib.common:
  swagger:
    enabled: true
    title: "Api Documentation"
    version: "0.0.1"
    ignored-parameter-types:
      - javax.servlet.http.HttpServletRequest
      - java.security.Principal
      - com.example.sample.controller.SampleController.Query
#      - org.springframework.security.core.Authentication


### Pages plugin
pagehelper:
  helper-dialect: oracle
  auto-runtime-dialect: true
  reasonable: false
  support-methods-arguments: true
  params: count=countSql