server:
  port: 8029

mib:
  core:
    common:
      enabled: true

spring:
  profiles:
    active: dev

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://10.100.10.44:8999/auth/realms/spring-micro-main

