server:
  port: 8029

#mib:
#  core:
#    common:
#      enabled: true



spring:
  profiles:
    active: dev
  main.allow-bean-definition-overriding: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://10.100.10.44:8999/auth/realms/spring-micro-main
  web:
    locale-resolver: accept_header
    locale: uz

mib.common:
  swagger:
    enabled: true
    title: "Api Documentation"
    version: "0.0.1"
    ignored-parameter-types:
      - javax.servlet.http.HttpServletRequest
      - java.security.Principal
      - com.example.sample.controller.TestController.Query
#      - org.springframework.security.core.Authentication
